#ifndef _ERRNO_H
#define _ERRNO_H

#define E2BIG		1
#define EACCES		2
#define EADDRINUSE	3
#define EADDRNOTAVAIL	4
#define EAFNOSUPPORT	5
#define EAGAIN		6
#define EALREADY	7
#define EBUSY		8
#define ECANCELED	9
#define ECHILD		10
#define ECONNABORTED	11
#define ECONNREFUSED	12
#define ECONNRESET	13
#define EDEADLK		14
#define EDESTADDRREQ	15
#define EDOM		16
#define EDQUOT		17
#define EEXIST		18
#define EFAULT		19
#define EFBIG		20
#define EHOSTUNREACH	21
#define EIDRM		22
#define EILSEQ		23
#define EINPROGRESS	24
#define EINTR		25
#define EINVAL		26
#define EIO		26
#define EISCONN		27
#define EISDIR		28
#define ELOOP		29
#define EMFILE		30
#define EMLINK		31
#define EMSGSIZE	32
#define EMULTIHOP	33
#define ENAMETOOLONG	34
#define ENETDOWN	35
#define ENETRESET	36
#define ENETUNREACH	37
#define ENFILE		38
#define ENOBUFS		39
#define ENODATA		40
#define ENODEV		41
#define ENOENT		42
#define ENOEXEC		43
#define ENOLCK		44
#define ENOLINK		45
#define ENOMEM		46
#define ENOMSG		47
#define ENOPROTOOPT	48
#define ENOSPC		49
#define ENOSR		50
#define ENOSTR		51
#define ENOSYS		52
#define ENOTCONN	53
#define ENOTDIR		54
#define ENOTEMPTY	55
#define ENOTRECOVERABLE	56
#define ENOTSOCK	57
#define ENOTSUP		58
#define ENOTTY		59
#define ENXIO		60
#define EOPNOTSUPP	61
#define EOVERFLOW	62
#define EOWNERDEAD	63
#define EPERM		64
#define EPIPE		65
#define EPROTO		66
#define EPROTONOSUPPORT	67
#define EPROTOTYPE	68
#define ERANGE		69
#define EROFS		70
#define ESPIPE		71
#define ESRCH		72
#define ESTALE		73
#define ETIME		74
#define ETIMEDOUT	75
#define ETXTBSY		76
#define EWOULDBLOCK	77
#define EXDEV		78

#endif /* _ERRNO_H */
