OBJ_FILES += $(DRIVERS_DIR)/ata/ata_subr.o \
             $(DRIVERS_DIR)/ata/ata_init.o \
	     $(DRIVERS_DIR)/ata/ata_pio.o \
             $(DRIVERS_DIR)/ata/ata_request.o \
             $(DRIVERS_DIR)/ata/ata_dma.o \
             $(DRIVERS_DIR)/ata/bus_master.o
