LIBC_OBJ += sys/wait/waitpid.o \
            sys/wait/wait.o \
            sys/stat/chmod.o \
            sys/stat/stat.o \
            sys/stat/mkdir.o \
            sys/stat/mknod.o \
            sys/stat/umask.o \
            sys/stat/fstat.o \
            sys/stat/lstat.o
