#ifndef ERRNO_H
#define ERRNO_H

#define E2BIG		1
#define EACCES		2
#define EADDRINUSE	3
#define EADDRNOTAVAIL	4
#define EAFNOSUPPORT	5
#define EAGAIN		6
#define EALREADY	7
#define EBADF		8
#define EBUSY		9
#define ECANCELED	10
#define ECHILD		11
#define ECONNABORTED	12
#define ECONNREFUSED	13
#define ECONNRESET	14
#define EDEADLK		15
#define EDESTADDRREQ	16
#define EDOM		17
#define EDQUOT		18
#define EEXIST		19
#define EFAULT		20
#define EFBIG		21
#define EHOSTUNREACH	22
#define EIDRM		23
#define EILSEQ		24
#define EINPROGRESS	25
#define EINTR		26
#define EINVAL		27
#define EIO		28
#define EISCONN		29
#define EISDIR		30
#define ELOOP		31
#define EMFILE		32
#define EMLINK		33
#define EMSGSIZE	34
#define EMULTIHOP	35
#define ENAMETOOLONG	36
#define ENETDOWN	37
#define ENETRESET	38
#define ENETUNREACH	39
#define ENFILE		40
#define ENOBUFS		41
#define ENODATA		42
#define ENODEV		43
#define ENOENT		44
#define ENOEXEC		45
#define ENOLCK		46
#define ENOLINK		47
#define ENOMEM		48
#define ENOMSG		49
#define ENOPROTOOPT	50
#define ENOSPC		51
#define ENOSR		52
#define ENOSTR		53
#define ENOSYS		54
#define ENOTCONN	55
#define ENOTDIR		56
#define ENOTEMPTY	57
#define ENOTRECOVERABLE	58
#define ENOTSOCK	59
#define ENOTSUP		60
#define ENOTTY		61
#define ENXIO		62
#define EOPNOTSUPP	63
#define EOVERFLOW	64
#define EOWNERDEAD	65
#define EPERM		66
#define EPIPE		67
#define EPROTO		68
#define EPROTONOSUPPORT	69
#define EPROTOTYPE	70
#define ERANGE		71
#define EROFS		72
#define ESPIPE		73
#define ESRCH		74
#define ESTALE		75
#define ETIME		76
#define ETIMEDOUT	77
#define ETXTBSY		78
#define EWOULDBLOCK	79
#define EXDEV		80

#endif /* ERRNO_H */
