#ifndef _PCI_H
#define _PCI_H

#define PCI_CONFIG_ADDRESS	0xCF8
#define PCI_CONFIG_DATA		0xCFC

/* Maximum number of buses */
#define PCI_MAX_BUSES		256
/* Maximum number of devices per bus */
#define PCI_MAX_DEVICES		32
/* Maximum number of functions per device */
#define PCI_MAX_FUNCTIONS	8

struct pci_entry {
	int flag;
	int bus;
	int device;
	int function;
};

enum pci_class_codes {
	PCI_CLASS_CODE_UNCLASSIFIED,
	PCI_CLASS_CODE_MASS_STORAGE,
	PCI_CLASS_CODE_NETWORK,
	PCI_CLASS_CODE_DISPLAY,
	PCI_CLASS_CODE_MULTIMEDIA,
	PCI_CLASS_CODE_MEMORY,
	PCI_CLASS_CODE_BRIDGE,
	PCI_CLASS_CODE_SIMPLE_COM,
	PCI_CLASS_CODE_BASE_SYSTEM_PERIPHERAL,
	PCI_CLASS_CODE_INPUT_DEVICE,
	PCI_CLASS_CODE_DOCKING_STATION,
	PCI_CLASS_CODE_PROCESSOR,
	PCI_CLASS_CODE_SERIAL_BUS,
	PCI_CLASS_CODE_WIRELESS,
	PCI_CLASS_CODE_INTELLIGENT,
	PCI_CLASS_CODE_SATELLITE_COM,
	PCI_CLASS_CODE_ENCRYPTION,
	PCI_CLASS_CODE_SIGNAL_PROCESSING,
	PCI_CLASS_CODE_PROCESSING_ACCEL,
	PCI_CLASS_CODE_NON_ESSENTIAL,
	PCI_CLASS_CODE_CO_PROCESSOR = 0x3F,
	PCI_CLASS_CODE_UNASSIGNED = 0xFF
};

void pci_init(void);

#endif /* _PCI_H */
