OBJ_FILES += $(KERNEL_DIR)/main.o \
             $(KERNEL_DIR)/printk.o \
             $(KERNEL_DIR)/proc.o \
             $(KERNEL_DIR)/schedule.o \
             $(KERNEL_DIR)/mutex.o \
             $(KERNEL_DIR)/sys.o \
             $(KERNEL_DIR)/signal.o \
             $(KERNEL_DIR)/exec_elf.o \
             $(KERNEL_DIR)/exec_elf32.o \
             $(KERNEL_DIR)/dump.o
