OBJ_FILES += $(DRIVERS_DIR)/driver_tab.o \
             $(DRIVERS_DIR)/8250_uart.o \
             $(DRIVERS_DIR)/tty.o \
	     $(DRIVERS_DIR)/init.o \
             $(DRIVERS_DIR)/fb.o \
             $(DRIVERS_DIR)/fbcon.o \
             $(DRIVERS_DIR)/psf.o \
             $(DRIVERS_DIR)/virtual_console.o \
             $(DRIVERS_DIR)/pit.o \
             $(DRIVERS_DIR)/timer.o \
             $(DRIVERS_DIR)/cmos.o

include $(DRIVERS_DIR)/acpi/Makefile
include $(DRIVERS_DIR)/pci/Makefile
