OBJ_FILES += $(FS_DIR)/ext2/attribute.o \
             $(FS_DIR)/ext2/super.o \
             $(FS_DIR)/ext2/inode.o \
             $(FS_DIR)/ext2/balloc.o \
	     $(FS_DIR)/ext2/namei.o \
             $(FS_DIR)/ext2/open.o \
             $(FS_DIR)/ext2/ialloc.o
