LIBC_OBJ += string/memcpy.o \
            string/memset.o \
            string/memmove.o \
            string/memcmp.o \
            string/strcpy.o \
            string/strncpy.o \
            string/strlen.o
