LIBC_OBJ += unistd/read.o \
            unistd/write.o \
            unistd/fork.o \
            unistd/execve.o \
            unistd/sync.o \
            unistd/close.o \
            unistd/lseek.o \
            unistd/dup.o \
            unistd/dup2.o \
            unistd/_exit.o
