LIBC_OBJ += unistd/read.o \
            unistd/write.o \
            unistd/fork.o \
            unistd/execve.o \
            unistd/sync.o \
            unistd/close.o \
            unistd/lseek.o \
            unistd/dup.o \
            unistd/dup2.o \
            unistd/_exit.o \
            unistd/access.o \
            unistd/alarm.o \
            unistd/chdir.o \
            unistd/chown.o \
            unistd/getegid.o \
            unistd/geteuid.o \
            unistd/getgid.o \
            unistd/getpgid.o \
            unistd/getpgrp.o \
            unistd/getpid.o \
            unistd/getppid.o \
            unistd/getsid.o \
            unistd/getuid.o

